#configuracion de acceso a BD
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop 
  #estrategia de generacion de base de datos
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_bookito
    username: postgres
    password: admin
    
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    
server:
  port: 8090 